// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-U-8uQPc-_mcqofcPQzlUdK1QixxU1vs',
    appId: '1:1069398158655:web:c1cb70b4bce66043ac778a',
    messagingSenderId: '1069398158655',
    projectId: 'vetapp-60906',
    authDomain: 'vetapp-60906.firebaseapp.com',
    storageBucket: 'vetapp-60906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8iDII4PvRZs2UQ9Y-oaThUpyaiw2Xxs0',
    appId: '1:1069398158655:android:f0062110301643fcac778a',
    messagingSenderId: '1069398158655',
    projectId: 'vetapp-60906',
    storageBucket: 'vetapp-60906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl41IWzxxNkf6hESFr19deju0-uYTQ7w8',
    appId: '1:1069398158655:ios:a24719f4d0b10a4eac778a',
    messagingSenderId: '1069398158655',
    projectId: 'vetapp-60906',
    storageBucket: 'vetapp-60906.appspot.com',
    iosBundleId: 'com.example.vetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl41IWzxxNkf6hESFr19deju0-uYTQ7w8',
    appId: '1:1069398158655:ios:a24719f4d0b10a4eac778a',
    messagingSenderId: '1069398158655',
    projectId: 'vetapp-60906',
    storageBucket: 'vetapp-60906.appspot.com',
    iosBundleId: 'com.example.vetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-U-8uQPc-_mcqofcPQzlUdK1QixxU1vs',
    appId: '1:1069398158655:web:f460c9243306d4a8ac778a',
    messagingSenderId: '1069398158655',
    projectId: 'vetapp-60906',
    authDomain: 'vetapp-60906.firebaseapp.com',
    storageBucket: 'vetapp-60906.appspot.com',
  );
}
